# Colors (Paper Theme)
# window:
#   opacity: 0.85
colors:
  # Default colors
  primary:
    background: '#000000'
    foreground: '#ffffff'
  cursor:
    text: '#F81CE5'
    cursor: '#ffffff'

  # Normal colors
  normal:
    black: '#000000'
    red: '#fe0100'
    green: '#33ff00'
    yellow: '#feff00'
    blue: '#0066ff'
    magenta: '#cc00ff'
    cyan: '#00ffff'
    white: '#d0d0d0'

  # Bright colors
  bright:
    black: '#808080'
    red: '#fe0100'
    green: '#33ff00'
    yellow: '#feff00'
    blue: '#0066ff'
    magenta: '#cc00ff'
    cyan: '#00ffff'
    white: '#FFFFFF'
# Colors (Hyper)
# colors:
#   # Default colors
#   primary:
#     background: '0x000000'
#     foreground: '0xffffff'
#   cursor:
#     text: '0xF81CE5'
#     cursor: '0xffffff'
#   # Normal colors
#   normal:
#     black:   '0x000000'
#     red:     '0xfe0100'
#     green:   '0x33ff00'
#     yellow:  '0xfeff00'
#     blue:    '0x0066ff'
#     magenta: '0xcc00ff'
#     cyan:    '0x00ffff'
#     white:   '0xd0d0d0'
#   # Bright colors
#   bright:
#     black:   '0x808080'
#     red:     '0xfe0100'
#     green:   '0x33ff00'
#     yellow:  '0xfeff00'
#     blue:    '0x0066ff'
#     magenta: '0xcc00ff'
#     cyan:    '0x00ffff'
#     white:   '0xFFFFFF'
font:
  size: 12
  # bold:
  # family: Victor Mono
  # style: Bold
  # bold_italic:
  # family: Victor Mono
  # style: Bold Italic
  # italic:
  # family: Victor Mono
  # style: Italic
  # normal:
  # family: Victor Mono
  # style: Regular
  # bold:
  #   family: MonoLisa
  #   style: Bold
  # bold_italic:
  #   family: MonoLisa
  #   style: Bold Italic
  # italic:
  #   family: MonoLisa
  #   style: Italic
  # normal:
  #   family: MonoLisa
  #   style: Light
  bold:
    family: NotoSansM Nerd Font Mono
    style: Bold
  bold_italic:
    family: NotoSansM Nerd Font Mono
    style: Bold Italic
  italic:
    family: NotoSansM Nerd Font Mono
    style: Italic
  normal:
    family: NotoSansM Nerd Font Mono
    style: Regular
key_bindings:
  - chars: "\eb"
    key: Left
    mods: Alt
  - chars: "\ef"
    key: Right
    mods: Alt
  - chars: "\eOH"
    key: Left
    mode: AppCursor
    mods: Command
  - chars: "\eOF"
    key: Right
    mode: AppCursor
    mods: Command
  - chars: "\x15"
    key: Back
    mods: Command
  - chars: "\e"
    key: Back
    mods: Alt
live_config_reload: true
theme: hyper

env:
  TERM: xterm-256color
